### ISSUE TITLE
[Bug]: Custom Report Bar Chart : Impossible to edit legends

### ISSUE THREAD

**Issue by LoganMacKinnon** [TorqIT/pimcore#44]
[#7110](https://github.com/pimcore/pimcore/issues/7110)

Although somebody submitted a PR for this issue, it doesn't appear to be working on Pimcore Version 10.5.13.

For some reason an unrelated label appears when using bar charts, specifically `ext-chart-series-bar-#`.

![image](https://user-images.githubusercontent.com/61194412/213266338-91e32bb8-30d4-4df2-bd77-1dce1684f3c3.png)

Not sure where it's coming from - you can see the configuration for the above screenshot here:

```
pimcore:
    custom_report:
        definitions:
            ProductsPerSupplier:
                name: ProductsPerSupplier
                sql: ''
                dataSourceConfig:
                    -
                        sql: 'COUNT(p.oo_id), s.name, SUM(CASE WHEN p.status = ''Active'' THEN 1 ELSE 0 END) AS activeProducts, SUM(CASE WHEN p.status = ''Discontinued'' THEN 1 ELSE 0 END) as discontinuedProducts'
                        from: 'object_CTXBASEPRD AS p INNER JOIN object_CTXSUP AS s ON p.supplier__id = s.oo_id'
                        where: ''
                        groupby: supplier__id
                        type: sql
                columnConfiguration:
                    -
                        name: name
                        display: true
                        export: true
                        order: true
                        width: null
                        label: Supplier
                        filter: null
                        displayType: null
                        filter_drilldown: null
                        columnAction: null
                        id: extModel429-7
                    -
                        name: COUNT(p.oo_id)
                        display: true
                        export: true
                        order: true
                        width: ''
                        label: Products
                        id: extModel429-8
                    -
                        name: activeProducts
                        display: true
                        export: true
                        order: true
                        width: ''
                        label: Active
                        id: extModel429-9
                    -
                        name: discontinuedProducts
                        display: true
                        export: true
                        order: true
                        width: ''
                        label: Discontinued
                        id: extModel429-10
                niceName: 'Products Per Supplier'
                group: ''
                groupIconClass: ''
                iconClass: ''
                menuShortcut: true
                reportClass: ''
                chartType: bar
                pieColumn: Count(oo_id)
                pieLabelColumn: name
                xAxis: name
                yAxis:
                    - Count(p.oo_id)
                    - activeProducts
                    - discontinuedProducts
                modificationDate: 1674065597
                creationDate: 1674049907
                shareGlobally: true
                sharedUserNames: {  }
                sharedRoleNames: {  }

```
